import { EmojiCategory } from "@/types/ui";

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Smileys",
    emojis: ["😀","😃","😄","😁","😆","😅","😂","🤣","😊","😇","🙂","🙃","😉","😌","😍","🥰","😘","😜","🤪","😎","🥳","😏","😒","😔","🥺","😢","😭","😡","🤔","😴"],
  },
  {
    name: "Gestures",
    emojis: ["👍","👎","👌","👊","✊","✌️","🤞","🤟","👋","👏","🙌","🙏","💪","✍️","🤝"],
  },
  {
    name: "Hearts",
    emojis: ["❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔","❣️","💕","💞","💓","💗","💖","💘"],
  },
  {
    name: "Party",
    emojis: ["🎉","✨","🔥","⭐","💥","🎈","🎂","🎄","🎆","🎇","🧨","🎊","🌈","☀️","🌙","❄️"],
  },
];

export const EMOJI_KEYWORDS: Record<string, string> = {
  "😀": "smile happy grin face laugh",
  "😃": "smile happy grin face laugh",
  "😄": "smile happy grin face laugh",
  "😁": "smile happy grin face laugh",
  "😆": "smile happy grin face laugh",
  "😅": "smile sweat face laugh happy",
  "😂": "cry laugh tears lol face",
  "🤣": "cry laugh tears lol face roll",
  "😊": "smile blush happy face",
  "😇": "halo angel face innocent",
  "🙂": "smile face slight",
  "🙃": "upside down face smile",
  "😉": "wink face blink",
  "😌": "relieved face peace calm",
  "😍": "heart eyes love face adore",
  "🥰": "hearts face love blush adore",
  "😘": "kiss face heart blow",
  "😜": "wink tongue face silly",
  "🤪": "crazy face eyes silly",
  "😎": "cool glasses sunglasses face",
  "🥳": "party celebrate face horn hat",
  "😏": "smirk face sly smirk",
  "😒": "unamused face unhappy",
  "😔": "sad pensive face",
  "🥺": "pleading beg eyes face",
  "😢": "cry sad tear face",
  "😭": "cry sob loud tears face",
  "😡": "angry mad red face pout",
  "🤔": "think face look hand",
  "😴": "sleep zzz face tired snore",
  "👍": "like thumbs up good yes ok hand",
  "👎": "dislike thumbs down bad no hand",
  "👌": "ok hand fine correct perfect",
  "👊": "fist punch hand bang",
  "✊": "fist hand power raised",
  "✌️": "peace victory hand fingers sign",
  "🤞": "fingers crossed luck hand sign",
  "🤟": "love you hand fingers sign",
  "👋": "wave hello goodbye hand",
  "👏": "clap hands applaud congrats",
  "🙌": "celebrate hands raise hooray",
  "🙏": "please pray hands thank hope",
  "💪": "muscle flex strength power",
  "✍️": "write hand pen pencil draw",
  "🤝": "shake hands agree partner",
  "❤️": "heart love red",
  "🧡": "heart love orange",
  "💛": "heart love yellow",
  "💚": "heart love green",
  "💙": "heart love blue",
  "💜": "heart love purple",
  "🖤": "heart love black",
  "🤍": "heart love white",
  "🤎": "heart love brown",
  "💔": "heart broken split sad",
  "❣️": "heart exclamation sign love",
  "💕": "hearts double pink love",
  "💞": "hearts revolving pink love",
  "💓": "heart beating pink love",
  "💗": "heart growing pink love",
  "💖": "heart sparkle pink love",
  "💘": "heart arrow cupid love",
  "🎉": "party popper celebrate horn fun",
  "✨": "sparkles shine star glitter",
  "🔥": "fire hot burn lit element",
  "⭐": "star yellow star glow shine",
  "💥": "explosion bang boom spark",
  "🎈": "balloon birthday party toy",
  "🎂": "cake birthday dessert sweet food",
  "🎄": "christmas tree holiday celebration",
  "🎆": "fireworks celebration sky light",
  "🎇": "sparkler celebration light",
  "🧨": "firecracker celebration red",
  "🎊": "ball confetti celebrate party decoration",
  "🌈": "rainbow sky colorful nature",
  "☀️": "sun hot day light weather",
  "🌙": "moon night dark sky space",
  "❄️": "snowflake winter cold ice snow",
};

export const QUICK_REACTIONS = ["👍", "❤️", "😂", "😮", "😢", "🙏"];
